deviceName: 127.0.0.1:62001
platformName: Android
platformVersion: 4.4.2
sessionOverride: True
#app: os.path.dirname(os.path.abspath("."))+ "/app/znbwl.apk"
noReset: True
appPackage: com.pdswp.su.smartcalendar
appActivity: com.pdswp.su.smartcalendar.WelcomeNote
ip: 127.0.0.1
port: 4723
resetKeyboard: True
unicodeKeyboard: True
automationName: uiautomator2